version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7 # new versions must be at least 7 days old
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7 # new versions must be at least 7 days old
  - package-ecosystem: cargo
    directory: /native
    schedule:
      interval: monthly
    open-pull-requests-limit: 0 # security updates ONLY
